name: camera_with_rtmp
description: Camera plugin with rtmp streaming included.
version: 0.1.1
homepage: https://github.com/pinkfish/flutter_rtmppublisher

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^1.6.7
  video_player: ^0.10.9+1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.9.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whelksoft.camera_with_rtmp
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
