name: camera_with_rtmp
description: Camera plugin with rtmp streaming included.
version: 0.1.0
homepage: https://github.com/pinkfish/flutter_rtmppublisher

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whelksoft.rtmppublisher
        pluginClass: RtmppublisherPlugin
      ios:
        pluginClass: RtmppublisherPlugin
