name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter    
    steps:
      - run: sudo mkdir ${ANDROID_HOME}/ndk
        continue-on-error: true
      - name: Cache ndk
        uses: actions/cache@v2
        with:
          path: |
            ${ANDROID_HOME}/ndk
          key: ${{ runner.os }}-ndk
      - uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
        continue-on-error: true
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.1'
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
        working-directory: example
